apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-seed
  namespace: fitbook

spec:
  backoffLimit: 3

  template:
    metadata:
      labels:
        app: mongodb-seed

    spec:
      restartPolicy: OnFailure

      containers:
        - name: mongodb-seed
          image: nennaa/fitbook-backend:76c1cf7cbe9550453471a88b99599b0e1f4d2cbc
          imagePullPolicy: IfNotPresent

          command:
            - python
            - init_sample_data.py

          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: fitbook-mongodb-secret
                  key: MONGODB_URI

            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fitbook-config
                  key: MONGO_DB_NAME

            - name: PYTHONUNBUFFERED
              value: "1"